export const PAYROLL_BUSINESS_STAGE_ORDER = [
  'DATA_READINESS',
  'PAYROLL_PREPARATION',
  'REVIEW_APPROVAL',
  'PAYMENT',
  'RECONCILIATION_CLOSE',
] as const;

export type PayrollBusinessStage = (typeof PAYROLL_BUSINESS_STAGE_ORDER)[number];
export const PAYROLL_BUSINESS_STAGE_COUNT = PAYROLL_BUSINESS_STAGE_ORDER.length;

const STAGE_BY_STATE: Record<string, PayrollBusinessStage> = {
  DRAFT: 'DATA_READINESS',
  SUBMITTED: 'PAYROLL_PREPARATION',
  INGESTING: 'PAYROLL_PREPARATION',
  AI_VALIDATING: 'PAYROLL_PREPARATION',
  EXCEPTION_FOUND: 'DATA_READINESS',
  EXCEPTION_REVIEW: 'DATA_READINESS',
  CLIENT_ACTION_REQUIRED: 'DATA_READINESS',
  CLIENT_RESUBMITTED: 'PAYROLL_PREPARATION',
  VALIDATED: 'PAYROLL_PREPARATION',
  STANDARDIZED: 'PAYROLL_PREPARATION',
  PROCESSOR_REVIEW: 'PAYROLL_PREPARATION',
  CONTROLLER_REVIEW: 'REVIEW_APPROVAL',
  REVISION_REQUIRED: 'DATA_READINESS',
  DATA_APPROVED: 'REVIEW_APPROVAL',
  PAYROLL_FINALIZED: 'REVIEW_APPROVAL',
  PAYMENT_INSTRUCTION_READY: 'PAYMENT',
  PAYMENT_APPROVAL_PENDING: 'PAYMENT',
  APPROVED_FOR_PAYMENT: 'PAYMENT',
  DISBURSEMENT_PROCESSING: 'PAYMENT',
  PROOF_UPLOADED: 'PAYMENT',
  RECONCILIATION: 'RECONCILIATION_CLOSE',
  PAYMENT_EXCEPTION: 'RECONCILIATION_CLOSE',
  COMPLETED: 'RECONCILIATION_CLOSE',
  REJECTED: 'DATA_READINESS',
  CANCELLED: 'DATA_READINESS',
};

export const BUSINESS_STAGE_LABELS: Record<PayrollBusinessStage, string> = {
  DATA_READINESS: 'Data Readiness',
  PAYROLL_PREPARATION: 'Payroll Preparation',
  REVIEW_APPROVAL: 'Review & Approval',
  PAYMENT: 'Payment',
  RECONCILIATION_CLOSE: 'Reconciliation & Close',
};

export function payrollBusinessStage(state: unknown): PayrollBusinessStage {
  return STAGE_BY_STATE[String(state || '').toUpperCase()] || 'DATA_READINESS';
}

export function payrollBusinessStageLabel(state: unknown) {
  return BUSINESS_STAGE_LABELS[payrollBusinessStage(state)];
}

export function payrollBusinessStageIndex(state: unknown, piStatus?: unknown, recStatus?: unknown) {
  if (recStatus && /MATCH|COMPLETE/i.test(String(recStatus))) return PAYROLL_BUSINESS_STAGE_COUNT;
  if (piStatus && /PAID|COMPLETED|RECONCILED/i.test(String(piStatus))) return PAYROLL_BUSINESS_STAGE_COUNT;
  return PAYROLL_BUSINESS_STAGE_ORDER.indexOf(payrollBusinessStage(state)) + 1;
}
