version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "chore(deps)"
